### Register a new user
POST {{baseUrl}}register
Content-Type: application/json

{
  "username": "benjamino",
  "password": "securePassword123"
}

###

### Login and get JWT token
POST {{baseUrl}}login
Content-Type: application/json

{
  "username": "benjamin",
  "password": "securePassword123"
}

###


### Login and get JWT token
POST {{baseUrl}}login
Content-Type: application/json

{
  "username": "benjamino",
  "password": "securePassword123"
}

###



### Login and get JWT token
POST {{baseUrl}}login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

### Create a new playlist (requires token)
POST {{baseUrl}}playlists
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE5OTA0LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.D9DBb2VFgGtNASipAAA_wJeN7oqWBT7lAnXLit9pN_c
Content-Type: application/json

{
  "name": "Workout"
}

###


### Add a song to a particular playlist (from external API)
POST {{baseUrl}}playlists/2/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE1OTEyLCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.dYOrgU_dnymXVD4s_VPg43ZtIUNoILZnHtbK9WVUfxU
Content-Type: application/json

{
  "externalId": 123456,
  "title": "Lose Yourself",
  "artist": "Eminem",
  "album": "8 Mile"
}

###


### Add a song to a particular playlist (from external API)
POST {{baseUrl}}playlists/2/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE1OTEyLCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.dYOrgU_dnymXVD4s_VPg43ZtIUNoILZnHtbK9WVUfxU
Content-Type: application/json

{
  "externalId": 422202502,
  "title": "Too Good At Goodbyes",
  "artist": "Sam Smith",
  "album": "The Thrill Of It All (Special Edition)"
}

###

### Add a song to a particular playlist (from external API)
POST {{baseUrl}}playlists/2/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE5OTA0LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.D9DBb2VFgGtNASipAAA_wJeN7oqWBT7lAnXLit9pN_c
Content-Type: application/json

{
  "externalId": 70079770,
  "title": "All of Me",
  "artist": "John Legend",
  "album": "Love In The Future (Expanded Edition)"
}

###


### Get all playlists for specific user (requires token)
GET {{baseUrl}}playlists
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE5OTA0LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.D9DBb2VFgGtNASipAAA_wJeN7oqWBT7lAnXLit9pN_c
Content-Type: application/json

###

### Get all songs for a particular playlist
GET {{baseUrl}}playlists/2/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE5OTA0LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.D9DBb2VFgGtNASipAAA_wJeN7oqWBT7lAnXLit9pN_c
Content-Type: application/json


###

### Remove song from particular playlist (User)
DELETE {{baseUrl}}playlists/2/songs/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE5OTA0LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.D9DBb2VFgGtNASipAAA_wJeN7oqWBT7lAnXLit9pN_c
Content-Type: application/json


###

### Delete a particual playlist as user
DELETE {{baseUrl}}playlists/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE5OTA0LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.D9DBb2VFgGtNASipAAA_wJeN7oqWBT7lAnXLit9pN_c
Content-Type: application/json


###
### Update playlist name (user)
PUT {{baseUrl}}playlists/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE5OTA0LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.D9DBb2VFgGtNASipAAA_wJeN7oqWBT7lAnXLit9pN_c
Content-Type: application/json

{
  "name": "Evening Chill"
}

###



### Get all users (require admin role)
GET {{baseUrl}}admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIkJlbmphbWluIFJpbm9cIiIsInN1YiI6ImJlbmphbWlubyIsImV4cCI6MTc2MTEyODE5Niwicm9sZXMiOiJVc2VyLEFkbWluIiwidXNlcm5hbWUiOiJiZW5qYW1pbm8ifQ.xMDMQ3EI_iQEhBNJ4V3v5tb8ieeseEtkFBfU1uyeQkk
Content-Type: application/json

###

### Delete by username (require admin role)
DELETE {{baseUrl}}admin/users/benjamin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoiYmVuamFtaW5vIiwiZXhwIjoxNzYxMjE5OTA0LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6ImJlbmphbWlubyJ9.D9DBb2VFgGtNASipAAA_wJeN7oqWBT7lAnXLit9pN_c
Content-Type: application/json

###


### Get all songs from own db (require admin role)
GET {{baseUrl}}admin/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIkJlbmphbWluIFJpbm9cIiIsInN1YiI6ImJlbmphbWlubyIsImV4cCI6MTc2MTEyODE5Niwicm9sZXMiOiJVc2VyLEFkbWluIiwidXNlcm5hbWUiOiJiZW5qYW1pbm8ifQ.xMDMQ3EI_iQEhBNJ4V3v5tb8ieeseEtkFBfU1uyeQkk
Content-Type: application/json

###

### Add role to user (require admin role)
PATCH {{baseUrl}}admin/users/benjamino/role
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIkJlbmphbWluIFJpbm9cIiIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzYxMTI3NTk3LCJyb2xlcyI6IkFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiJ9.CtKFg8h7JQSO-Xfe6x1-CcDoQ8bDUNUEBnyTjpQou7M
Content-Type: application/json

{
  "roleName": "Admin"
}

###
